'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace AliveIdeaService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Marca", [Namespace]:="http://schemas.datacontract.org/2004/07/Entities"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Marca
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private DescripcionCortaField As String
        
        Private DescripcionLargaField As String
        
        Private IdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MargenField As Decimal
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SloganField As String
        
        Private VisibilidadPrecioField As Boolean
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property DescripcionCorta() As String
            Get
                Return Me.DescripcionCortaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DescripcionCortaField, value) <> true) Then
                    Me.DescripcionCortaField = value
                    Me.RaisePropertyChanged("DescripcionCorta")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property DescripcionLarga() As String
            Get
                Return Me.DescripcionLargaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DescripcionLargaField, value) <> true) Then
                    Me.DescripcionLargaField = value
                    Me.RaisePropertyChanged("DescripcionLarga")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Id() As Integer
            Get
                Return Me.IdField
            End Get
            Set
                If (Me.IdField.Equals(value) <> true) Then
                    Me.IdField = value
                    Me.RaisePropertyChanged("Id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Margen() As Decimal
            Get
                Return Me.MargenField
            End Get
            Set
                If (Me.MargenField.Equals(value) <> true) Then
                    Me.MargenField = value
                    Me.RaisePropertyChanged("Margen")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Slogan() As String
            Get
                Return Me.SloganField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SloganField, value) <> true) Then
                    Me.SloganField = value
                    Me.RaisePropertyChanged("Slogan")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property VisibilidadPrecio() As Boolean
            Get
                Return Me.VisibilidadPrecioField
            End Get
            Set
                If (Me.VisibilidadPrecioField.Equals(value) <> true) Then
                    Me.VisibilidadPrecioField = value
                    Me.RaisePropertyChanged("VisibilidadPrecio")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="AliveIdeaService.IAliveIdeaService")>  _
    Public Interface IAliveIdeaService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IAliveIdeaService/ObtenerMarcas", ReplyAction:="http://tempuri.org/IAliveIdeaService/ObtenerMarcasResponse")>  _
        Function ObtenerMarcas() As AliveIdeaService.Marca()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IAliveIdeaService/ObtenerMarcas", ReplyAction:="http://tempuri.org/IAliveIdeaService/ObtenerMarcasResponse")>  _
        Function ObtenerMarcasAsync() As System.Threading.Tasks.Task(Of AliveIdeaService.Marca())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IAliveIdeaService/CrearMarca", ReplyAction:="http://tempuri.org/IAliveIdeaService/CrearMarcaResponse")>  _
        Function CrearMarca(ByVal marca As AliveIdeaService.Marca) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IAliveIdeaService/CrearMarca", ReplyAction:="http://tempuri.org/IAliveIdeaService/CrearMarcaResponse")>  _
        Function CrearMarcaAsync(ByVal marca As AliveIdeaService.Marca) As System.Threading.Tasks.Task(Of Integer)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IAliveIdeaServiceChannel
        Inherits AliveIdeaService.IAliveIdeaService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class AliveIdeaServiceClient
        Inherits System.ServiceModel.ClientBase(Of AliveIdeaService.IAliveIdeaService)
        Implements AliveIdeaService.IAliveIdeaService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function ObtenerMarcas() As AliveIdeaService.Marca() Implements AliveIdeaService.IAliveIdeaService.ObtenerMarcas
            Return MyBase.Channel.ObtenerMarcas
        End Function
        
        Public Function ObtenerMarcasAsync() As System.Threading.Tasks.Task(Of AliveIdeaService.Marca()) Implements AliveIdeaService.IAliveIdeaService.ObtenerMarcasAsync
            Return MyBase.Channel.ObtenerMarcasAsync
        End Function
        
        Public Function CrearMarca(ByVal marca As AliveIdeaService.Marca) As Integer Implements AliveIdeaService.IAliveIdeaService.CrearMarca
            Return MyBase.Channel.CrearMarca(marca)
        End Function
        
        Public Function CrearMarcaAsync(ByVal marca As AliveIdeaService.Marca) As System.Threading.Tasks.Task(Of Integer) Implements AliveIdeaService.IAliveIdeaService.CrearMarcaAsync
            Return MyBase.Channel.CrearMarcaAsync(marca)
        End Function
    End Class
End Namespace
